In [82]:
# importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier


In [83]:
# reading data
df = pd.read_csv(r"D:\hotel_bookings.csv\hotel_bookings.csv")
df.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  children  babies  \
0                        0                     0       2       0.0       0   
1                        0                     0       2       0.0       0   
2                        0                     1       1       0.0       0   
3                        0                     1       1       0.0       0   
4                        0                     2       2       0.0       0   

  meal country market_segment distribution_channel  is_repeated_guest  \
0   BB     PRT         Direct               Direct                  0   
1   BB     PRT         Direct               Direct                  0   
2   BB     GBR         Direct               Direct                  0   
3   BB     GBR      Corporate            Corporate                  0   
4   BB     GBR      Online TA                TA/TO                  0   

   previous_cancellations  previous_bookings_not_canceled reserved_room_type  \
0                       0                               0                  C   
1                       0                               0                  C   
2                       0                               0                  A   
3                       0                               0                  A   
4                       0                               0                  A   

  assigned_room_type  booking_changes deposit_type  agent  company  \
0                  C                3   No Deposit    NaN      NaN   
1                  C                4   No Deposit    NaN      NaN   
2                  C                0   No Deposit    NaN      NaN   
3                  A                0   No Deposit  304.0      NaN   
4                  A                0   No Deposit  240.0      NaN   

   days_in_waiting_list customer_type   adr  required_car_parking_spaces  \
0                     0     Transient   0.0                            0   
1                     0     Transient   0.0                            0   
2                     0     Transient  75.0                            0   
3                     0     Transient  75.0                            0   
4                     0     Transient  98.0                            0   

   total_of_special_requests reservation_status reservation_status_date  
0                          0          Check-Out              2015-07-01  
1                          0          Check-Out              2015-07-01  
2                          0          Check-Out              2015-07-02  
3                          0          Check-Out              2015-07-02  
4                          1          Check-Out              2015-07-03

In [84]:
#dropping columns that are not useful

u= ['days_in_waiting_list', 'arrival_date_year', 'arrival_date_year', 'assigned_room_type', 'booking_changes', 'reservation_status', 'days_in_waiting_list']

df.drop(u, axis = 1, inplace = True)

In [85]:
df.head(10)

hotel  is_canceled  lead_time arrival_date_month  \
0  Resort Hotel            0        342               July   
1  Resort Hotel            0        737               July   
2  Resort Hotel            0          7               July   
3  Resort Hotel            0         13               July   
4  Resort Hotel            0         14               July   
5  Resort Hotel            0         14               July   
6  Resort Hotel            0          0               July   
7  Resort Hotel            0          9               July   
8  Resort Hotel            1         85               July   
9  Resort Hotel            1         75               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   
5                        27                          1   
6                        27                          1   
7                        27                          1   
8                        27                          1   
9                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  children  babies  \
0                        0                     0       2       0.0       0   
1                        0                     0       2       0.0       0   
2                        0                     1       1       0.0       0   
3                        0                     1       1       0.0       0   
4                        0                     2       2       0.0       0   
5                        0                     2       2       0.0       0   
6                        0                     2       2       0.0       0   
7                        0                     2       2       0.0       0   
8                        0                     3       2       0.0       0   
9                        0                     3       2       0.0       0   

  meal country market_segment distribution_channel  is_repeated_guest  \
0   BB     PRT         Direct               Direct                  0   
1   BB     PRT         Direct               Direct                  0   
2   BB     GBR         Direct               Direct                  0   
3   BB     GBR      Corporate            Corporate                  0   
4   BB     GBR      Online TA                TA/TO                  0   
5   BB     GBR      Online TA                TA/TO                  0   
6   BB     PRT         Direct               Direct                  0   
7   FB     PRT         Direct               Direct                  0   
8   BB     PRT      Online TA                TA/TO                  0   
9   HB     PRT  Offline TA/TO                TA/TO                  0   

   previous_cancellations  previous_bookings_not_canceled reserved_room_type  \
0                       0                               0                  C   
1                       0                               0                  C   
2                       0                               0                  A   
3                       0                               0                  A   
4                       0                               0                  A   
5                       0                               0                  A   
6                       0                               0                  C   
7                       0                               0                  C   
8                       0                               0                  A   
9                       0                               0                  D   

  deposit_type  agent  company customer_type    adr  \
0   No Deposit    NaN      NaN     Transient    0.0   
1   No Deposit    NaN      NaN    

In [86]:
# creating numerical and categorical dataframes

x = [col for col in df.columns if df[col].dtype == 'O']
new_df = df[x]
new_df.head()

hotel arrival_date_month meal country market_segment  \
0  Resort Hotel               July   BB     PRT         Direct   
1  Resort Hotel               July   BB     PRT         Direct   
2  Resort Hotel               July   BB     GBR         Direct   
3  Resort Hotel               July   BB     GBR      Corporate   
4  Resort Hotel               July   BB     GBR      Online TA   

  distribution_channel reserved_room_type deposit_type customer_type  \
0               Direct                  C   No Deposit     Transient   
1               Direct                  C   No Deposit     Transient   
2               Direct                  A   No Deposit     Transient   
3            Corporate                  A   No Deposit     Transient   
4                TA/TO                  A   No Deposit     Transient   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03

In [87]:
new_df['reservation_status_date'] = pd.to_datetime(new_df['reservation_status_date'])

new_df['year'] = new_df['reservation_status_date'].dt.year
new_df['month'] = new_df['reservation_status_date'].dt.month
new_df['day'] = new_df['reservation_status_date'].dt.day
new_df.drop(['reservation_status_date','arrival_date_month'] , axis = 1, inplace = True)


In [88]:
# printing unique values of each column
for c in new_df.columns:
    print(f"{c}: \n{new_df[c].unique()}\n")

hotel: 
['Resort Hotel' 'City Hotel']

meal: 
['BB' 'FB' 'HB' 'SC' 'Undefined']

country: 
['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' nan 'ROU' 'NOR' 'OMN' 'ARG' 'POL'
 'DEU' 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST'
 'CZE' 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR'
 'UKR' 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO'
 'ISR' 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM'
 'HRV' 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY'
 'KWT' 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN'
 'SYC' 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB'
 'CMR' 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI'
 'SAU' 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB'
 'NPL' 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA'
 'KHM' 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP'
 'GLP' 'KEN' 'LIE' 'GNB' 'MNE' 'UMI'

In [89]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [90]:
# encoding categorical variables

new_df['hotel'] = new_df['hotel'].map({'Resort Hotel' : 0, 'City Hotel' : 1})

new_df['meal'] = new_df['meal'].map({'BB' : 0, 'FB': 1, 'HB': 2, 'SC': 3, 'Undefined': 4})
 
new_df['country']=le.fit_transform(new_df['country'])

new_df['market_segment'] = new_df['market_segment'].map({'Direct': 0, 'Corporate': 1, 'Online TA': 2, 'Offline TA/TO': 3, 'Complementary': 4, 'Groups': 5, 'Undefined': 6, 'Aviation': 7})

new_df['distribution_channel'] = new_df['distribution_channel'].map({'Direct': 0, 'Corporate': 1, 'TA/TO': 2, 'Undefined': 3, 'GDS': 4})

new_df['reserved_room_type'] = new_df['reserved_room_type'].map({'C': 0, 'A': 1, 'D': 2, 'E': 3, 'G': 4, 'F': 5, 'H': 6, 'L': 7, 'B': 8})

new_df['deposit_type'] = new_df['deposit_type'].map({'No Deposit': 0, 'Refundable': 1, 'Non Refund': 3})

new_df['customer_type'] = new_df['customer_type'].map({'Transient': 0, 'Contract': 1, 'Transient-Party': 2, 'Group': 3})

new_df['year'] = new_df['year'].map({2015: 0, 2014: 1, 2016: 2, 2017: 3})
new_df['country']

0         135
1         135
2          59
3          59
4          59
         ... 
119385     15
119386     56
119387     43
119388     59
119389     43
Name: country, Length: 119390, dtype: int32

In [91]:
sec_df = df.drop(columns = x, axis = 1)
sec_df['adr'] = sec_df['adr'].fillna(value = sec_df['adr'].mean())

In [92]:
sec_df.head()

is_canceled  lead_time  arrival_date_week_number  \
0            0        342                        27   
1            0        737                        27   
2            0          7                        27   
3            0         13                        27   
4            0         14                        27   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                          1                        0                     0   
1                          1                        0                     0   
2                          1                        0                     1   
3                          1                        0                     1   
4                          1                        0                     2   

   adults  children  babies  is_repeated_guest  previous_cancellations  \
0       2       0.0       0                  0                       0   
1       2       0.0       0                  0                       0   
2       1       0.0       0                  0                       0   
3       1       0.0       0                  0                       0   
4       2       0.0       0                  0                       0   

   previous_bookings_not_canceled  agent  company   adr  \
0                               0    NaN      NaN   0.0   
1                               0    NaN      NaN   0.0   
2                               0    NaN      NaN  75.0   
3                               0  304.0      NaN  75.0   
4                               0  240.0      NaN  98.0   

   required_car_parking_spaces  total_of_special_requests  
0                            0                          0  
1                            0                          0  
2                            0                          0  
3                            0                          0  
4                            0                          1

In [93]:
X = pd.concat([new_df, sec_df], axis = 1)
y = new_df['country']
X=X[['market_segment','reserved_room_type','deposit_type','customer_type','agent']]
X

market_segment  reserved_room_type  deposit_type  customer_type  agent
0                    0                 0.0             0              0    NaN
1                    0                 0.0             0              0    NaN
2                    0                 1.0             0              0    NaN
3                    1                 1.0             0              0  304.0
4                    2                 1.0             0              0  240.0
...                ...                 ...           ...            ...    ...
119385               3                 1.0             0              0  394.0
119386               2                 3.0             0              0    9.0
119387               2                 2.0             0              0    9.0
119388               2                 1.0             0              0   89.0
119389               2                 1.0             0              0    9.0

[119390 rows x 5 columns]

In [94]:
# splitting data into training set and test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [95]:
X_train.fillna(0,inplace=True)
X_test.fillna(0,inplace=True)
y_train.fillna(0,inplace=True)
y_test.fillna(0,inplace=True)


# DECISION TREE CLASSIFIER

In [98]:
d = DecisionTreeClassifier()
d.fit(X_train, y_train)

y_pred = d.predict(X_test)

ad = accuracy_score(y_test, y_pred)
mat = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy Score of Decision Tree is : {ad}")
print(f"Confusion Matrix : \n{mat}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Decision Tree is : 0.46461177653069774
Confusion Matrix : 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00       106
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00        16
           6       0.00      0.00      0.00        68
           7       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         2
          11       0.33      0.01      0.01       131
          12       0.67      0.03      0.05       391
          13       0.00      0.00      0.00         3
          15       0.82      0.04      0.08       691
          16       0.

# END