In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns

In [13]:
import pickle
import math

In [2]:
df = pd.read_csv('D:\Semester 4\AI\hotel_bookings.csv')
df['total_nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
df.fillna(0, inplace = True)
df.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  agent  company  \
0                        0                     0       2  ...    0.0      0.0   
1                        0                     0       2  ...    0.0      0.0   
2                        0                     1       1  ...    0.0      0.0   
3                        0                     1       1  ...  304.0      0.0   
4                        0                     2       2  ...  240.0      0.0   

  days_in_waiting_list customer_type   adr required_car_parking_spaces  \
0                    0     Transient   0.0                           0   
1                    0     Transient   0.0                           0   
2                    0     Transient  75.0                           0   
3                    0     Transient  75.0                           0   
4                    0     Transient  98.0                           0   

   total_of_special_requests  reservation_status  reservation_status_date  \
0                          0           Check-Out               2015-07-01   
1                          0           Check-Out               2015-07-01   
2                          0           Check-Out               2015-07-02   
3                          0           Check-Out               2015-07-02   
4                          1           Check-Out               2015-07-03   

  total_nights  
0            0  
1            0  
2            1  
3            1  
4            2  

[5 rows x 33 columns]

In [3]:
correlation = df.corr()['total_nights'].abs().sort_values(ascending = False)
correlation

total_nights                      1.000000
stays_in_week_nights              0.941005
stays_in_weekend_nights           0.762790
agent                             0.208637
lead_time                         0.157167
is_repeated_guest                 0.106626
adults                            0.105249
booking_changes                   0.096498
total_of_special_requests         0.079259
adr                               0.067945
company                           0.063793
previous_bookings_not_canceled    0.053049
children                          0.050865
arrival_date_year                 0.031438
arrival_date_day_of_month         0.027408
required_car_parking_spaces       0.025794
days_in_waiting_list              0.022652
babies                            0.022283
arrival_date_week_number          0.018719
is_canceled                       0.017779
previous_cancellations            0.015429
Name: total_nights, dtype: float64

In [4]:
df2 = pd.DataFrame()

df2['stays_in_week_nights']=df['stays_in_week_nights']
df2['stays_in_weekend_nights']=df['stays_in_weekend_nights']
df2['agent']=df['agent']
df2['is_repeated_guest']=df['is_repeated_guest']
df2['total_nights']=df['total_nights']
df2

stays_in_week_nights  stays_in_weekend_nights  agent  \
0                          0                        0    0.0   
1                          0                        0    0.0   
2                          1                        0    0.0   
3                          1                        0  304.0   
4                          2                        0  240.0   
...                      ...                      ...    ...   
119385                     5                        2  394.0   
119386                     5                        2    9.0   
119387                     5                        2    9.0   
119388                     5                        2   89.0   
119389                     7                        2    9.0   

        is_repeated_guest  total_nights  
0                       0             0  
1                       0             0  
2                       0             1  
3                       0             1  
4                       0             2  
...                   ...           ...  
119385                  0             7  
119386                  0             7  
119387                  0             7  
119388                  0             7  
119389                  0             9  

[119390 rows x 5 columns]

In [5]:
X=df2.drop('total_nights',axis=1)
y = df['total_nights']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [7]:
X.shape,y.shape

((119390, 4), (119390,))

In [8]:
y_train.head(), y_test.head()

(79940    0
 18792    1
 32048    2
 65506    3
 26743    9
 Name: total_nights, dtype: int64,
 48165    2
 7138     7
 23257    1
 73176    2
 27057    1
 Name: total_nights, dtype: int64)

In [12]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

y_pred_dtc = dtc.predict(X_test)

acc_dtc = accuracy_score(y_test, y_pred_dtc)
conf = confusion_matrix(y_test, y_pred_dtc)
clf_report = classification_report(y_test, y_pred_dtc)

print(f"Accuracy Score of Decision Tree is : {acc_dtc}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Decision Tree is : 0.9997766423765251
Confusion Matrix : 
[[ 223    0    0 ...    0    0    0]
 [   0 6230    0 ...    0    0    0]
 [   0    0 8235 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    0]]
Classification Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       223
           1       1.00      1.00      1.00      6230
           2       1.00      1.00      1.00      8235
           3       1.00      1.00      1.00      8247
           4       1.00      1.00      1.00      5199
           5       1.00      1.00      1.00      2376
           6       1.00      1.00      1.00      1167
           7       1.00      1.00      1.00      2600
           8       1.00      1.00      1.00       337
           9       1.00      1.00      1.00       257
          10       1.00      1.00      1.00       336
          11       1.0

In [14]:
pickle.dump(dtc,open('model.pkl','wb'))
model=pickle.load(open('model.pkl','rb'))